# ============================================
# BrandOS - Initial Setup Script for D:\Server
# Run this script ONCE to setup BrandOS
# Usage: .\deploy-configs\setup-brandos.ps1
# ============================================

param(
    [string]$DbHost = "192.168.0.41",
    [string]$DbPort = "5432",
    [string]$DbName = "brandos_db",
    [string]$DbUser = "brandos_user",
    [string]$DbPassword = "",
    [string]$JwtSecret = "",
    [string]$OpenAiKey = ""
)

$BaseDir = "D:\Server"
$AppName = "brandos"
$AppPort = 40200

Write-Host "`n============================================" -ForegroundColor Cyan
Write-Host " BrandOS Setup Script" -ForegroundColor Cyan
Write-Host " Port: $AppPort | Domain: brandos.jlcgroup.co" -ForegroundColor Cyan
Write-Host "============================================`n" -ForegroundColor Cyan

# Step 1: Check prerequisites
Write-Host "[1/8] Checking prerequisites..." -ForegroundColor Yellow
$nodeVersion = node --version 2>&1
$pnpmVersion = pnpm --version 2>&1
Write-Host "  Node.js: $nodeVersion" -ForegroundColor Green
Write-Host "  pnpm: $pnpmVersion" -ForegroundColor Green

# Step 2: Create folder structure
Write-Host "[2/8] Creating folder structure..." -ForegroundColor Yellow
@("apps\$AppName", "deploy\$AppName", "run\$AppName", "logs\$AppName") | ForEach-Object {
    $path = "$BaseDir\$_"
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "  Created: $path" -ForegroundColor Green
    } else {
        Write-Host "  Exists: $path" -ForegroundColor Gray
    }
}

# Step 3: Clone or pull repo
Write-Host "[3/8] Setting up source code..." -ForegroundColor Yellow
$sourcePath = "$BaseDir\apps\$AppName"
if (-not (Test-Path "$sourcePath\.git")) {
    Write-Host "  Cloning from GitHub..." -ForegroundColor Yellow
    git clone https://github.com/jlc-group/brandos $sourcePath
} else {
    Write-Host "  Pulling latest code..." -ForegroundColor Yellow
    Set-Location $sourcePath
    git pull origin main
}

# Step 4: Install dependencies
Write-Host "[4/8] Installing dependencies..." -ForegroundColor Yellow
Set-Location $sourcePath
pnpm install

# Step 5: Create .env file
Write-Host "[5/8] Creating environment file..." -ForegroundColor Yellow
$envPath = "$BaseDir\run\$AppName\.env"

if ($DbPassword -eq "") {
    $DbPassword = Read-Host "  Enter PostgreSQL password for brandos_user"
}
if ($JwtSecret -eq "") {
    $JwtSecret = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 32 | ForEach-Object { [char]$_ })
    Write-Host "  Generated JWT Secret: $JwtSecret" -ForegroundColor Gray
}
if ($OpenAiKey -eq "") {
    $OpenAiKey = Read-Host "  Enter OpenAI API Key (sk-...)"
}

$envContent = @"
# BrandOS Environment Variables
# Generated by setup-brandos.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Database
DATABASE_URL=postgresql://${DbUser}:${DbPassword}@${DbHost}:${DbPort}/${DbName}

# Auth
JWT_SECRET=${JwtSecret}

# App
NODE_ENV=production
PORT=${AppPort}

# LLM
OPENAI_API_KEY=${OpenAiKey}

# App Identity
VITE_APP_TITLE=BrandOS
VITE_APP_ID=brandos
"@

$envContent | Out-File -FilePath $envPath -Encoding UTF8
Write-Host "  .env created at: $envPath" -ForegroundColor Green

# Step 6: Run database migration
Write-Host "[6/8] Running database migration..." -ForegroundColor Yellow
Set-Location $sourcePath
Copy-Item $envPath ".env" -Force
pnpm db:push
Write-Host "  Database migration complete!" -ForegroundColor Green

# Step 7: Build production
Write-Host "[7/8] Building production bundle..." -ForegroundColor Yellow
pnpm build
Write-Host "  Build complete!" -ForegroundColor Green

# Step 8: Copy nginx config
Write-Host "[8/8] Setting up Nginx config..." -ForegroundColor Yellow
$nginxConf = "$sourcePath\deploy-configs\nginx\brandos.jlcgroup.co.conf"
$nginxDest = "$BaseDir\nginx\conf\sites-enabled\brandos.jlcgroup.co.conf"
if (Test-Path $nginxConf) {
    Copy-Item $nginxConf $nginxDest -Force
    Write-Host "  Nginx config copied to: $nginxDest" -ForegroundColor Green
    Write-Host "  Remember to reload Nginx (run as Administrator):" -ForegroundColor Yellow
    Write-Host "  nginx -s reload" -ForegroundColor White
}

Write-Host "`n============================================" -ForegroundColor Green
Write-Host " BrandOS Setup Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host " Next steps:" -ForegroundColor White
Write-Host " 1. Add BrandOS to ecosystem.config.js (see deploy-configs\pm2\brandos.ecosystem.js)" -ForegroundColor White
Write-Host " 2. Run: pm2 start ecosystem.config.js --only brandos" -ForegroundColor White
Write-Host " 3. Reload Nginx as Administrator: nginx -s reload" -ForegroundColor White
Write-Host " 4. Add DNS: brandos.jlcgroup.co -> 192.168.0.41" -ForegroundColor White
Write-Host " 5. Open: http://brandos.jlcgroup.co" -ForegroundColor White
Write-Host "============================================`n" -ForegroundColor Green
